### ISSUE TITLE
№ 3072 "Гусеничный асфальтоукладчик АСФ-Г-4-04"

### ISSUE THREAD

**Issue by NAM-Soft** [gwisp2/stamp-finder-monorepo#1]
Здравствуйте.
Почему отсутствует марка № 3072 "Гусеничный асфальтоукладчик АСФ-Г-4-04"?

**Comment by gwisp2** [comment]
Это скорее проблема в [gwisp2/russian-stamps](https://github.com/gwisp2/russian-stamps).
Не знаю, почему она не добавилась вместе с 3071, но теперь она есть.
